// CUSTOMIZE ERROR CODE FOR STATUS CODE
// CAN ALSO USE LIBRARY SUCH AS THE HTTP-STATUS-CODES INSTEAD OF SETTING UP THE CUSTOMIZE STATUS CODE

exports.constants = {
    VALIDATION_ERROR: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND : 404,
    SERVER_ERROR: 500
}